targets:
  $default:
    builders:
      reyveld|sgen:
        enabled: true

builders:
  sgen:
    import: "package:reyveld/builder.dart"
    builder_factories: ["sgenBuilder"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    runs_before: ["source_gen|combining_builder"]
    applies_builders: ["source_gen|combining_builder"]
