name: reyveld
description: A sample command-line application with basic argument parsing.
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-180.3.beta

dependencies:
  uuid: any # Used for generating unique hashes.
  hashlib: ^1.21.0 # TODO: Use this in Lua.
  talker: ^4.5.1 # Used for logging. Seriously, this logger is really good. Go check it out.
  version: ^3.0.2 # Used for versioning of Reyveld.
  xml: ^6.5.0 # The xml package is used as the building blocks of SKit.
  yaml: ^3.1.3 
  rxdart: ^0.28.0 # Used specifically for merging streams (the header, unloaded & loaded archives) when saving a skit.
  lua_dardo_async: any # Used for running lua scripts.
  encrypt: ^5.0.3 # Used for encrypting/decrypting files.
  async: ^2.13.0 
  glob: ^2.1.3 # Used for filtering files in a directory.
  pointycastle: ^3.9.1 # Used for RSA signing.
  basic_utils: ^5.7.0
  cli_spin: ^1.0.1 # Used for the loading spinner.
  chalkdart: ^3.0.5 # Used for colorizing text.
  convert: ^3.1.2
  image: ^4.5.4
  ini: ^2.1.0
  open_url: ^2.0.1
  http: ^1.4.0
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: any # Used for building SFactories for SObjects.
  source_gen: any # Used for generating SFactories.
  analyzer: any # Used to find SGen annotations, used for building SFactories.
