name: Build

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.6.5
      - name: Fetch Dependencies
        run: dart pub get .
      - name: Make Build Directories
        run: "mkdir -p build/releases/${{ matrix.platform }} &&
          mkdir ./scripts/installers/${{ matrix.platform }}/lib"
      - name: Build Executable
        run: dart compile exe --define=DEBUG=false ./lib/main.dart --target-os ${{ matrix.platform }} -o build/releases/${{ matrix.platform }}/${{ matrix.output}}
      - name: Moving Installers
        run: ${{ matrix.add-install-command }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: build/releases/${{ matrix.platform }}/
          retention-days: 14
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            output: reyveld.elf
            add-install-command: "cp -r ./scripts/installers/linux/ ./build/releases/"
          - os: windows-latest
            platform: windows
            output: reyveld.exe
            add-install-command: "Copy-Item -Recurse -Path ./scripts/installers/windows/ -Destination ./build/releases/ -Force"
          # - os: macos-latest
          #   platform: macos
          #   output: reyveld.app
          #   path-to-squirrel-library: ./src/squirrel3/squirrel/libsquirrel.so
          #   rename-squirrel-to: squirrel.dylib
